### ISSUE TITLE
ProviderWrapper 能封装更彻底点吗？不需要用户再写java.String('aa')  new Request({...})

### ISSUE THREAD

**Issue by sunchuanleihit** [apache/dubbo-js#100]
ProviderWrapper 能封装更彻底点吗？不需要用户再写java.String('aa')  new Request({...})

只需要传基本类型比如demoMethod('nihao', 4, {email: "sunchuanleihit@163.com"})

这个翻译师应该可以根据api jar的参数类型做到

类似下面这样
![image](https://user-images.githubusercontent.com/5242501/57365011-dc913080-71b6-11e9-8ebe-a01156ebf2e3.png)

设计argumentMap 应该就是想帮助用户自动转换类型，但是现在argumentMap全是空的function, 是还没时间继续往下做吗

谢谢

**Comment by hufeng** [comment]
@sunchuanleihit 你说的对，是的 最开始也是这样设计的，但是我们碰到一个非常难搞的问题

就是java这边可能是方法重载，

比如，
public class User {
    public void sayHello(String name) {}

    public void sayHello(long id) {}

    public void sayHello(double id) {}
}

对于到js里面有些类型对不上，导致很难处理，
所以当时和@creasy2010 一起就设计成现在的样子

**Comment by sunchuanleihit** [comment]
是的，这个考虑为了通用性只能这么做，但是生产环境Dubbo Provider也不太可能提供一个重载的方法，我这边正在实现一个更彻底的封装，过两天提个pr

**Comment by hufeng** [comment]
@sunchuanleihit 不错可以作为一个备选的方案 比如加一个参数 可以切换生成代码的方式
