### ISSUE TITLE
enum好像现在不能用，序列化的内容格式有问题

### ISSUE THREAD

**Issue by sunchuanleihit** [apache/dubbo-js#101]

**Comment by hufeng** [comment]
是手写还是通过翻译师翻译出来的？

**Comment by sunchuanleihit** [comment]
翻译时翻译出来的

**Comment by hufeng** [comment]
@creasy2010 一起看下

**Comment by creasy2010** [comment]
@sunchuanleihit 我找了两个例子分别 对应 number与string类型的. 是可以的呀 . 
能把你不行的例子发出来吗 ? 
```typescript
export enum OnOff {
  OFF = 1,
  ON = 0,
}
//generate by interpret-cli dubbo2.js

export enum FlowState {
  INIT = 'INIT',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CONFIRMED = 'CONFIRMED',
  AUDITED = 'AUDITED',
  VOID = 'VOID',
}
//generate by interpret-cli dubbo2.js


```

**Comment by sunchuanleihit** [comment]
![image](https://user-images.githubusercontent.com/5242501/58305037-3df90680-7e29-11e9-87fe-b79be8488583.png)



![image](https://user-images.githubusercontent.com/5242501/58304987-1a35c080-7e29-11e9-8c8e-4864025f12c6.png)

![image](https://user-images.githubusercontent.com/5242501/58305001-26218280-7e29-11e9-9ff8-bbaff4bd699c.png)

翻译出来的不能直接使用

**Comment by creasy2010** [comment]
这个问题不应该的. 我们生产上也有很多enum类型的数据 ..  

我来试下..    再补一个单元测试

**Comment by creasy2010** [comment]
经过测试根本原因是这个issue报的问题: https://github.com/apache/incubator-dubbo-js/issues/100
