### ISSUE TITLE
现在dubbo.json中指定jar包中的Provider规则有点太粗暴，只能指定providerSuffix

### ISSUE THREAD

**Issue by sunchuanleihit** [apache/dubbo-js#104]
现在dubbo.json中指定jar包中的Provider规则有点太粗暴，只能指定providerSuffix，有些复杂的jar包内部有很多不统一的后缀，这个要怎么处理

**Comment by sunchuanleihit** [comment]
https://github.com/dubbo/js-for-apache-dubbo/pull/103

**Comment by hufeng** [comment]
是很暴力，😃因为之前我们团队内部的规范就是这样设计的 这块还要想下 @creasy2010 主要的麻烦点在哪里

**Comment by sunchuanleihit** [comment]
> 是很暴力，😃因为之前我们团队内部的规范就是这样设计的 这块还要想下 @creasy2010 主要的麻烦点在哪里

https://github.com/yokai-alley/jexpose  你们在jexpose里已经实现了根据正则表达式来查找Provider，只不过现在翻译师里还没用起来，我的pr里把1.4的jexpose 引进来了，没太多工作量，都是你们做过的工作，我这边测试也没发现什么问题

**Comment by hufeng** [comment]
3ks @sunchuanleihit ，主要翻译师这块是 @creasy2010 @hsiaosiyuan0 两个同学设计的

最近我们有两个同学去你们那了 ^_^  我来看看建个微信群 方便我们沟通

**Comment by sunchuanleihit** [comment]
> 3ks @sunchuanleihit ，主要翻译师这块是 @creasy2010 @hsiaosiyuan0 两个同学设计的
> 
> 最近我们有两个同学去你们那了 ^_^ 我来看看建个微信群 方便我们沟通

赞呐，这样就方便多了  github昵称同微信昵称😃

**Comment by xusd320** [comment]
@hufeng 大佬您好，关于dubbo.json我也有个疑问，目前只能在json中单个配置，如下
{
    "output": "./app/dubbo/providers",
    "entry": "com.alibaba.dubbo.demo1",
    "entryJarPath": "./jars/dubbo-samples-zookeeper-1.0-SNAPSHOT.jar",
    "libDirPath":   "./",
    "providerSuffix": "Provider"
}
如果项目里有多个java依赖要分别翻译，就需要配置多个json分别执行interpret，这样感觉有点麻烦，能否像egg-dubbo-rpc里配置一样支持传入一个array(如下)，一次配置多个依赖，一次性翻译呢？
[
  {
    "output": "./app/dubbo/providers",
    "entry": "com.alibaba.dubbo.demo1",
    "entryJarPath": "./jars/dubbo-samples-zookeeper-1.0-SNAPSHOT.jar",
    "libDirPath":   "./",
    "providerSuffix": "Provider"
 },
  {
    "output": "./app/dubbo/providers",
    "entry": "com.alibaba.dubbo.demo2",
    "entryJarPath": "./jars/dubbo-samples-rpc-1.0-SNAPSHOT.jar",
    "libDirPath":   "./",
    "providerSuffix": "Provider"
}
]。
目前我是基于interpret单独封装了一个脚本，但是用起来仍然不是很方便。
