### ISSUE TITLE
http://dubbo.io/js-for-apache-dubbo is not working

### ISSUE THREAD

**Issue by ralf0131** [apache/dubbo-js#107]
http://dubbo.io/js-for-apache-dubbo is not working.
It returns 404 File not found.

**Comment by hufeng** [comment]
@ralf0131 thanks, let me fix it.

**Comment by hufeng** [comment]
oops, sorry,   I have no authority for the time being.

**Comment by ralf0131** [comment]
I don't have the permission as well. What is the correct link? I can help to ask the Apache Infra guys to fix it.

**Comment by hufeng** [comment]
@ralf0131  We may need to check the code repository settings. 


<img width="915" alt="image" src="https://user-images.githubusercontent.com/533008/58058063-0163ab80-7b9a-11e9-948e-4ff26db88863.png">

**Comment by ralf0131** [comment]
dubbo.io will be shutdown in the near future. Would you please consider migrating the documentation to dubbo.apache.org? which is located under https://github.com/apache/incubator-dubbo-website

**Comment by hufeng** [comment]
@ralf0131 great,  So everyone will have a unified entrance. such as Golang, Python, Php dubbo ecosystem

**Comment by hufeng** [comment]
maybe migrating need a long distance time @ralf0131

**Comment by ralf0131** [comment]
No hurry, let's work on it!

**Comment by hufeng** [comment]
Are we making a plan?
for example..

## todos

- [ ] first thing 
- [ ] second

**Comment by ralf0131** [comment]
Hi, where is the source of http://dubbo.io/js-for-apache-dubbo ?

**Comment by hufeng** [comment]
https://github.com/apache/dubbo-js/tree/gh-pages

gh-pages branch

**Comment by ralf0131** [comment]
Hi, will it be possible to transfer the files to dubbo-website?

Recently the erlang documentation has been transferred. see https://github.com/apache/dubbo-website/pull/382

**Comment by rocky-zh** [comment]
If you make a few changes recently ,I suggest you can change the owner of this project。

**Comment by hufeng** [comment]
@rocky-zh Sorry , Now I am not the owner ,  I only have pull request permission

**Comment by ralf0131** [comment]
> If you make a few changes recently ,I suggest you can change the owner of this project。@hufeng

There is no ownership in Apache projects. Anyone can contribute to any projects if one wish to.
Once he/she get enough merit, committership will be granted, then PMC membership. So if you are interested, why not just participate? If you do not know how, ask questions, there are many people who are willing to help.
