### ISSUE TITLE
full rpc solution for javascript

### ISSUE THREAD

**Issue by rocky-zh** [apache/dubbo-js#118]
节假日看过go语言的dubbo-go实现，希望社区能专心做javascript的rpc解决方案，完整的实现dubbo for javascript。

- 完整的javascript 的provider、consumer
- 完整的javascript 相互调用其他语言dubbo实现
-  ......

Role: Consumer, Provider
Transport: HTTP, TCP
Codec: JsonRPC v2, Hessian v2
Registry: ZooKeeper
Cluster Strategy: Failover
Load Balance: Random
Filter: Echo Health Check
Cluster Strategy: Failfast/Failsafe/Failback/Forking
Load Balance: RoundRobin/LeastActive/ConsistentHash
TokenFilter/AccessLogFilter/CountFilter/ActiveLimitFilter/ExecuteLimitFilter/GenericFilter/TpsLimitFilter
Registry: etcd/k8s/consul
routing rule (dubbo v2.6.x)
metrics (dubbo v2.7.x) waiting dubbo's quota
dynamic configuration center & metadata center (dubbo v2.7.x)
tracing (dubbo ecosystem)

**Comment by hufeng** [comment]
思考过一样的问题，一起调研下
我一直困惑在怎么解决无缝调用，比如我们js暴露一个服务，java那边怎么无缝调用，是不是我们可以根据js代码生成java的代码

**Comment by rocky-zh** [comment]
如果用到protobuf,thrift

**Comment by hufeng** [comment]
@rocky-zh yes，我最近也在调研jsonschema，在想这个是不是更适合我们一点

**Comment by rocky-zh** [comment]
@hufeng https://github.com/cevio/dubbo.ts

**Comment by cevio** [comment]
> @rocky-zh yes，我最近也在调研jsonschema，在想这个是不是更适合我们一点

ajv模块做jsonschema校验，实测性能下降比较大。
