### ISSUE TITLE
报错：Please specify dubboSetting

### ISSUE THREAD

**Issue by huanghuiqi** [apache/dubbo-js#124]
你好，按照demo执行了一遍，报了Please specify dubboSetting的问题，请问这是什么原因呢？谢谢@_@。
![QQ截图20190716183446](https://user-images.githubusercontent.com/20414453/61287862-6cc3a580-a7f8-11e9-9fd5-e85a55baa15b.jpg)

**Comment by YouthLin** [comment]
相同的问题 怎么解的……
