### ISSUE TITLE
zookeeper的acl认证支持

### ISSUE THREAD

**Issue by xusd320** [apache/dubbo-js#130]
node-zookeeper-client本身是支持zk连接配置权限认证的，详见：https://www.npmjs.com/package/node-zookeeper-client#void-addauthinfoscheme-auth
dubbo2.js是否能添加相关支持, 在register中传入认证配置？如下：
{
  url: 'localhost:3128',
  authInfo: { scheme: 'digest', auth: 'user:123456' }
}

在调用zookooper.createClient之后调用zookeeper.addAuthInfo,即可实现认证。目前zookeeper-luester-client以及添加类似的支持了，详见https://github.com/node-modules/zookeeper-cluster-client/blob/ae1fce14da3b35e75e3bd602df31aea8f9b85bf3/lib/data_client.js#L19

**Comment by rocky-zh** [comment]
真不知道 这个项目到底在干什么，代码活跃度为0

**Comment by xusd320** [comment]
@rocky-zh 开始用的时候体验还不错，线上有些功能欠缺。我现在已经基于这个自己维护一套了

**Comment by xusd320** [comment]
https://github.com/apache/dubbo-js/pull/132
