### ISSUE TITLE
动态重置dubbo-js运行

### ISSUE THREAD

**Issue by wushanchao** [apache/dubbo-js#131]
**Describe the bug**
项目运行过程中，会注册中心突然变地址，或者dubbo服务down掉，重连不上服务。
现在的做法是，通过重启项目来重新初始化dubbo-js配置，来解决问题。
希望dubbo-js能提供一个重置运行的接口，使得无需重启项目就能重置dubbo-js运行。

**Comment by czewail** [comment]
我们也碰到了这个问题，节点变更, 大量 current state RETRY 和 Exception: CONNECTION_LOSS

**Comment by hufeng** [comment]
@wushanchao 可以我来考虑下

**Comment by wushanchao** [comment]
@hufeng 
大佬，dubbojs@3.0 什么时候发布。
zk状态问题还是很普遍的，现在有没有什么临时包紧急修复一下。

**Comment by hufeng** [comment]
预计下周可以发布

sam <notifications@github.com> 于2019年10月25日周五 上午11:04写道：
