### ISSUE TITLE
What does "dubboSetting" stand for?

### ISSUE THREAD

**Issue by pxmage** [apache/dubbo-js#136]
I tried to create a Dubbo object following the document
```javascript
// create dubbo object
const dubbo = new Dubbo<typeof service>({
  application: {name: 'node-dubbo'},
  // zookeeper address
  register: 'localhost:2181',
  service,
});
```
However, typescript told me that I need to pass a `dubboSetting` to the constructor, which is not listed on the document.

What am I supposed to pass to it?

**Comment by reallyimeric** [comment]
found it here
https://github.com/apache/dubbo-js/releases/tag/dubbo2.js%402.3.5

**Comment by pxmage** [comment]
@reallyimeric Thank you for the reply. ☺
