### ISSUE TITLE
`ts-simple-ast` is deprecated. Please update to `ts-morph`

### ISSUE THREAD

**Issue by AtarisMio** [apache/dubbo-js#150]
The `ts-simple-ast` is deprecated. Please update to `ts-morph`. #149 

@hufeng @creasy2010

**Comment by hufeng** [comment]
+1

**Comment by creasy2010** [comment]
我来升级下呢..

**Comment by AtarisMio** [comment]
@creasy2010 I've upgraded it in #149

**Comment by creasy2010** [comment]
@AtarisMio perfect!!!   
I am going to verify locally.
