### ISSUE TITLE
Missing comments in the translation process

### ISSUE THREAD

**Issue by creasy2010** [apache/dubbo-js#158]
**Describe the bug**
The translator's main responsibility is to convert the jar into a node, but the translation process currently loses the comments;
Because we can't get field comments or method comments from the jar package. This greatly affects the development experience.

** Possible solution**
1. Get the interface ast from the source [xxx.source.jar] code
2. Get it  from Api document like [swagger-dubbo](https://github.com/Sayi/swagger-dubbo)

**Comment by hufeng** [comment]
Yes
