### ISSUE TITLE
支持服务治理功能

### ISSUE THREAD

**Issue by wushanchao** [apache/dubbo-js#173]
从zk拿到服务的ip列表后，希望提供一个ip筛选的回调函数，从而支持服务治理。

**Comment by hufeng** [comment]
@wushanchao 能详细描述下场景嘛，小伙伴一起支持下

**Comment by wushanchao** [comment]
> @wushanchao 能详细描述下场景嘛，小伙伴一起支持下

@hufeng   已发pr，场景在pr中描述了，烦请review下。

**Comment by hufeng** [comment]
@wushanchao 👍👍👍
