### ISSUE TITLE
attachment里的参数dubbo服务取不到

### ISSUE THREAD

**Issue by shige8023** [apache/dubbo-js#181]
按照https://github.com/apache/dubbo-js/issues/72的示例配置了attachment
dubbo服务取不到
请问有没有详细的示例或者需要怎么排查问题

**Comment by yjua** [comment]
使用attachments是可以取到的
```
dubbo.use(async(ctx, next) => {
  ctx.attachments = {
    id: 'xx'
  }
  await next();
})
```
如上代码，如果获取不到应该是服务端设置问题吧
