### ISSUE TITLE
dubbo-js钉钉交流群

### ISSUE THREAD

**Issue by liqian008** [apache/dubbo-js#189]
> 使用attachment设置通用参数无效，发起请求时在consumer端就报错（未到达后端dubbo）

问题已解决： 
```
ctx.attachments = {
   traceId: 'xxxxxxx'
 }

按 https://github.com/apache/dubbo-js/issues/36的方法操作，nodejs可以成功设置，dubbo侧可以获取。

按https://github.com/apache/dubbo-js/issues/72 的方法操作，有报错（attachment非function）。

```

苦于无处交流，新建了个钉钉群
![dubo-js](https://user-images.githubusercontent.com/3658906/71705883-91e6b780-2e1c-11ea-9dee-57c9cd648d8f.jpeg)

**Comment by creasy2010** [comment]
Hello, we have created an official communication group, welcome to join .

![image](https://user-images.githubusercontent.com/1592277/71872262-d9d84800-3156-11ea-8620-80477b9af3a5.png)

**Comment by h1orz** [comment]
大佬们，二维码已过期😂

**Comment by hufeng** [comment]
好的，我来fixed下，有微信吗 我加HainLo下

HainLo ***@***.***> 于2021年6月21日周一 下午4:42写道：

**Comment by chenShengYa** [comment]
还能加嘛，微信搜索说账号异常

**Comment by ariesly15** [comment]
@liqian008 @hufeng @creasy2010 

我要进群，谁拉我一把

**Comment by DevinXian** [comment]
群二维码可否刷新
