### ISSUE TITLE
请教，如何支持动态设置attachment？

### ISSUE THREAD

**Issue by liqian008** [apache/dubbo-js#192]
在我司的dubbo实践规范中，会将web请求信息（如：登录用户uid，traceid，scheme，host，method，requestUrl等）对象写入attachment，供后端在必要时使用。

那么如何在不改动dubbo规范的情况下，做到在每次调用dubbo接口时，动态设置不同的attachment？

谢谢解答！

**Comment by liqian008** [comment]
已解决

**Comment by itmajing** [comment]
> 

请问怎么解决的，我这边也有同样的需求
