### ISSUE TITLE
对于dubbo的扩展点，dubbo-js有支持计划吗？

### ISSUE THREAD

**Issue by liqian008** [apache/dubbo-js#193]
RT，如Router，负载均衡，权重，扩展协议等，在此请教作者大大

![WechatIMG1314](https://user-images.githubusercontent.com/3658906/71864854-07fc5e80-313c-11ea-849f-fa05b8711982.png)

**Comment by hufeng** [comment]
@liqian008 负载均衡目前支持随机算法 其他的暂时还没有支持 可以一起支持一波 O(∩_∩)O

**Comment by hufeng** [comment]
@liqian008 3.0.0.的版本拖得有点久，目前先把这个发布出来，接下来就是全面的增强体验和功能
