### ISSUE TITLE
请问Dubbo.js是否支持调用后端的回声测试接口？

### ISSUE THREAD

**Issue by zewade** [apache/dubbo-js#205]
你好，我们这边可能想调用dubbo内置的回声测试接口。但看了一下dubbo.js似乎没办法调用api包之外的接口，想确定一下是否有办法调用回声测试接口。

回声测试用于检测服务是否可用，可以使用启动检查的check配置，也可以从代码中检测，dubbo中的所有服务自动实现EchoService接口，所以可以将任意的服务类型强转为EchoService
Spring配置

<dubbo:reference id="memberService" interface="com.xxx.MemberService" />
调用代码：

HelloService helloService = ctx.getBean("helloService"); 
EchoService echoService = (EchoService) helloService; // 强制转型为EchoService
// 回声测试可用性
String status = echoService.$echo("OK"); 
assert(status.equals("OK"));

**Comment by hufeng** [comment]
可以调用的，直接在proxyServer中封装对echo的声明
