### ISSUE TITLE
我应该使用那个dubbo版本呀？

### ISSUE THREAD

**Issue by weivea** [apache/dubbo-js#207]
我看example里边都是直接
`import {Context, Dubbo, setting} from 'dubbo-js';`

且`dubbo2.js`我看很久没有publish了，

npm上边没有 `dubbo-js` 这个包，

我是应该使用packages/dubbo 这个包么?

不太明白

**Comment by godkun** [comment]
3.0 最新的是 apache-dubbo-js 包 

2.x是 dubbo2.js 包

**Comment by hufeng** [comment]
apache-dubbo-js@3.0.0-rc6
