### ISSUE TITLE
file: es7/registry/registry.js    error:  Connot read property 'filter' of undefined

### ISSUE THREAD

**Issue by lileilei** [apache/dubbo-js#209]
version : "apache-dubbo-js": "^3.0.0-rc6"

![image](https://user-images.githubusercontent.com/7247859/80099014-5c6b0300-85a0-11ea-8a7f-3918d35982ed.png)

偶现这个错误，可能是因为新增的服务  消费端先提交了代码而zk中还未注册提供服务导致的原因 ?

**Comment by hufeng** [comment]
@lileilei ok， let me add more test suite, check this problem.
