### ISSUE TITLE
DirectlyDubbo不支持attachment 字段吗

### ISSUE THREAD

**Issue by springJia** [apache/dubbo-js#211]
请问DirectlyDubbo是否可以支持上下文传输数据 如 attachment 字段

**Comment by springJia** [comment]
如果可以在proxyService下面加一个类似这样的： ctx.attachments = args.shift();

**Comment by hufeng** [comment]
@springJia Let me check it。Directlydubbo is generally used for local debugging, but Dubo is still used production.

**Comment by hufeng** [comment]
@springJia oops, Yes, DirectlyDubbo was not supported attachment, Let me fixed it.
