### ISSUE TITLE
最新发现一个问题，java返回值中如果包含有success字段，在node端这个字段会丢失

### ISSUE THREAD

**Issue by Paul-wallace** [apache/dubbo-js#212]
**Describe the bug**
比如java端的返回值是{"errorCode":null,"errorMsg":null,"success":true}，
node端获取到的是{"errorCode":null,"errorMsg":null},
难道是这个success字段被dubbo2.js过滤了吗？

**Comment by hufeng** [comment]
dubbo2.jsJS does not filter any fields returned by Java services.

**Comment by hnsongbiao** [comment]
什么原因呢，success 输出只有 isSuccess
