### ISSUE TITLE
请问现在不支持redis吗？

### ISSUE THREAD

**Issue by lihxhit** [apache/dubbo-js#213]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by godkun** [comment]
不支持呢，支持redis有点太麻烦了，坑很多，后面考虑支持nacos解决这个问题

**Comment by hufeng** [comment]
Yes, it is not supported for the time being. In the production environment, the redis is not stable enough。
