### ISSUE TITLE
2.3.9版本，是否支持json序列化

### ISSUE THREAD

**Issue by January23** [apache/dubbo-js#225]
现在用hessian序列化，如果请求是类似这种对象：
 {
  param1:{
    param2:{
      x:1,
      y:2
    },
    param3:{
      a:'1'
    }
  }

那我在注册provider的时候，按下面的方式写会造成序列化失败,要对req中的其他对象也要java.combine。这样写起来就很麻烦，有没有更好的方式，谢谢
methods: {
      func1() {
        return [
          java.combine('com.xxxx.request', {
             param1:{
                param2:{
                   x:1,
                   y:2
                },
             param3:{
                a:'1'
             }
           }),
        ];
      },
    },

**Comment by hufeng** [comment]
We usually generate this part of the code automatically through a translator
