### ISSUE TITLE
dubbo.js can't reconnected to zookeeper and backend unless manually restarted it.

### ISSUE THREAD

**Issue by zewade** [apache/dubbo-js#226]
**Describe the bug**
We have integrated dubbo.js within serveral projects.But there is a issue often occured that dubbo.js sometime lost the connection to zookeeper when zk is not avilable for just a few minute that caused it can't find backend services. Now I tested the example of 'hello-koa' under dubbo.js source code to reproduce the issue.I appreciated that if someone can confirm about this issue or maybe just a misunderstand, or give some advices on how to resoved it.

**To Reproduce**
***1. download the  source code of dubbo.js and switch to master branch
***2. cd dubbo.js and use 'docker-compse up' to start the zookeeper cluster 3.5.6.
***3. compile the dubbo-demo java service under java folder then start it use 'java -jar java/dubbo-demo/dubbo-demo-provider/target/dubbo-demo-provider-2.7.4.1-jar-with-dependencies.jar'
***4. start the hello-koa,       cd example/hello-koa
yarn
yarn run debug:start
***5. Now make sure all services has been started and   if we use 'curl http://localhost:3000/hello', it would return message like
'Hello test, response form provider: 192.168.40.76:20880%'
***6.then close the zk cluster, we may see hello-koa print 'ZookeeperDisconnectedError: ZooKeeper was disconnected.'
***7.continue to close the java dubbo-demo service,hello-koa will print message like this:
  dubbo:socket-worker SocketWorker#1  =receive data=> 192.168.40.76:20880 +3m
  dubbo:decode-buffer body length 2 +3m
  dubbo:socket-worker SocketWorker#1 <=receive= heartbeat data. +0ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: false retry: 20 +10s
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 19 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 18 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 17 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +0ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 16 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 15 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +3ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 14 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 13 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 12 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +0ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 11 +1ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 10 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 9 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 8 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 7 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +0ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 6 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 5 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 4 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 3 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 2 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 1 +0ms
  dubbo:socket-worker SocketWorker#1 =connecting=> 192.168.40.76:20880 +3s
  dubbo:socket-worker SocketWorker#1 <=occur error=> 192.168.40.76:20880 Error: connect ECONNREFUSED 192.168.40.76:20880 +1ms
  dubbo:socket-worker SocketWorker#1 <=closed=> 192.168.40.76:20880 hasError: true retry: 0 +0ms
  dubbo:dubbo-agent socket-worker#192.168.40.76:20880 was closed. delete this socket worker +7m
  dubbo:dubbo-agent SocketAgent current agentHost-> [Map Iterator] {  } +0ms
  dubbo:scheduler SocketWorker#1 was close +2m
{
  time: '2020-12-10T06:09:02.424Z',
  pid: 14171,
  host: '192.168.40.76',
  type: 'ERR',
  msg: Error: socket-worker#192.168.40.76:20880 was closed. delete this socket worker
      at DubboAgent._clearCloseWorker (/Users/wade/Work/Projects/microservice/github/dubbo-js/packages/dubbo/es7/dubbo-agent.js:75:29)
      at Object.onClose (/Users/wade/Work/Projects/microservice/github/dubbo-js/packages/dubbo/es7/dubbo-agent.js:58:34)
      at SocketWorker._onClose (/Users/wade/Work/Projects/microservice/github/dubbo-js/packages/dubbo/es7/socket-worker.js:124:34)
      at Socket.emit (events.js:314:20)
      at Socket.EventEmitter.emit (domain.js:486:12)
      at TCP.<anonymous> (net.js:672:12)
***8.reopen the zk cluster and the backend java dubbo-demo service.
***9.check the zk to make sure the backend registered successfully.
***10.  use 'curl http://localhost:3000/hello' to test dubbo.js ,it will print message like this 
uuid:  invoke org.apache.dubbo.demo.DemoProvider#sayHello was error, requestId#5:Could not find any agent worker with org.apache.dubbo.demo.DemoProvider#1.0.0# agentList: 192.168.40.76:20880

and this cann't be recovered unless restart the 'hello-koa'.

**Expected behavior**
As restarting a service to fix it isn't acceptable for production enviroments and registry status of a application consists of many microservices is hard to monitor, we hope that dubbo.js can recover from zk connection disconnected automatic like the dubbo-java's behavior.

**Screenshots**

**Comment by hufeng** [comment]
in 4.0.0 we change node zookeeper library
