### ISSUE TITLE
dubbo-js Major update

### ISSUE THREAD

**Issue by hufeng** [apache/dubbo-js#229]
Dear all,

Thanks to the support of the vivo open source collaboration team, we have made a major update to dubbo-js!! ❤️👏

The new architecture is shown below:
![image](https://user-images.githubusercontent.com/533008/103256730-3e745e80-49c9-11eb-81ff-af565efe3d6c.png)

Major update

**[New Features]**

1. The core modules are re-split, abstracted into five core modules: consumer, server, registry, setting, and common
2. Added dubbo-server module to provide a complete basic capability of dubbo tcp server service
3. Added dubbo-server to accept dubbo requests, serialization and deserialization of request parameters
4. Added service registration capability, register to zookeeper and nacos
5. Enhance scheduling of requests by the scheduler, adopt the concept of fast error, improve error information, and be more precise
6. Enhance the underlying debug log of dubbo-server to facilitate quick location of problems
7. Enhance the dubbo url of dubbo-server registered to zk, add side, pid, generic, protocol, dynamic, category, anyhost, timestamp and other parameters
8. Enhanced extension dubbo-server supports middleware middleware mechanism, which can extend the life cycle of the entire call
9. Refactor the serialization implementation of dubbo requests and responses to keep consistent with the upstream version
10. Add an independent heartbeat management module to simplify the communication between consumer and server
11. Added nacos as the registration center

**[Bug fix]**

1. Fix serialization of decodeDubboResponse of dubbo-consumer and deserialization of err object of error response
2. Repair the heartbeat mechanism between the consumer and the server to avoid a large number of heartbeat storms. At present, 3. The server will reply immediately after receiving the heartbeat, and the consumer will check and send periodically.
3. Fix the version setting of dubboVersion of dubbo-consumer, this version should be the protocol version of dubbo protocal, not the version of dubbo library

## project structure

```text
```
$ tree -L 2
.
├── __tests__                                     (Unit test code-using jest framework)
│   ├── async-test.ts
│   ├── binary-test.ts
│   ├── byte-test.ts
│   ├── context-test.ts
│   ├── decode-buffer-test.ts
│   ├── directly-dubbo-test.ts
│   ├── dubbo-hessian-parameter-test.ts
│   ├── dubbo-server-test.ts
│   ├── dubbo-test.ts
│   ├── dubbo-timeout-test.ts
│   ├── dubbo-url-test.ts
│   ├── dubbox-test.ts
│   ├── go-test.ts
│   ├── heart-beat-test.ts
│   ├── providers
│   ├── request-id-test.ts
│   ├── setting-test.ts
│   ├── socket-worker-test.ts
│   ├── version-test.ts
│   └── zookeeper-test.ts
├── common                                         (The underlying public modules are mainly tools)
│   ├── byte.ts
│   ├── config.ts
│   ├── err.ts
│   ├── go.ts
│   └── util.ts
├── consumer                                      ( service consumer)
│   ├── directly-dubbo.ts
│   ├── dubbo-agent.ts
│   ├── dubbo-url.ts
│   ├── dubbo.ts
│   ├── queue.ts
│   ├── request-context.ts
│   ├── request-id.ts
│   ├── scheduler.ts
│   ├── socket-status.ts
│   ├── socket-worker.ts
│   └── statistics.ts
├── hessian.d.ts
├── index.ts                                      
├── registry                                     registry （zookeeper and nacos）
│   ├── index.ts
│   ├── registry-nacos.ts
│   ├── registry-zookeeper.ts
│   └── registry.ts
├── serialization                                 (dubbo protocal serialization)
│   ├── constants.ts
│   ├── decode-buffer.ts
│   ├── decode-hessian2.ts
│   ├── encode-hessian2.ts
│   ├── heartbeat.ts
│   └── request.ts
├── server                                        (dubbo service provider)
│   ├── response-context.ts
│   ├── server.ts
│   └── server_test.ts
├── setting                                      ( invoke setting such as group，version)
│   ├── index.ts
│   ├── type.ts
│   └── types.ts
└── types.ts
```
```

**Comment by rocky-zh** [comment]
good job!
