### ISSUE TITLE
apache-dubbo-js中为什么没有nacos方法了？

### ISSUE THREAD

**Issue by tanggd** [apache/dubbo-js#232]
"apache-dubbo-js": "^3.0.0-rc6"中为什么没有nacos？
const { Dubbo, java, setting, nacos } = require('apache-dubbo-js')  // nacos  => undefined
在node_modules里的apache-dubbo-js源码中没有发现nacos方法
![image](https://user-images.githubusercontent.com/23456667/109788595-6b9ff000-7c4a-11eb-839a-b6e94c03c044.png)

但是，你们github仓库源码里又有nacos方法，见下面连接：
https://github.com/apache/dubbo-js/blob/master/packages/dubbo/src/index.ts

**Comment by lmikoto** [comment]
same problem ! and how to use nacos

**Comment by Vwings** [comment]
`3.0.0-rc6` is published more than one year ago, the code is diffrent from current `master` branch. If you want to use now, maybe you can build and publish to your own npm repository, I have tried that and it works now. Don't know when this version will be published. #236

**Comment by hufeng** [comment]
4.0.0 Nacos registry
