### ISSUE TITLE
examples need to be updated

### ISSUE THREAD

**Issue by Vwings** [apache/dubbo-js#236]
I'm using `3.0.0-rc6` apache-dubbo-js, and try to run `hello-koa` example in `master` branch, some fields is not exist.
```
// IDubboService not exist
import {IDubboService} from 'apache-dubbo-js';
```

```
// DubboServernot exist
import {DubboServer} from 'apache-dubbo-js';
```
I wonder which version of `apache-dubbo-js` this example is using, if the API is changed, could you please update the demo project?

**Comment by Vwings** [comment]
Well, `3.0.0-rc6` is published more than one year ago, and it's code is not match with master branch. finally I clone the master branch, build, and published to my own npm repo. is there any plan to release this new version?

**Comment by hufeng** [comment]
in 4.0.0, we will improve our examples
