### ISSUE TITLE
模块“"apache-dubbo-js"”没有导出的成员“DubboServer”

### ISSUE THREAD

**Issue by oeliok** [apache/dubbo-js#246]
examples\hello-koa\src\dubbo\provider\dubbo-zookeeper.ts 示例中没有DubboServer，需要更新一下，还有就是看着案例做发现上手很难，能不能给个可用的。

**Comment by oeliok** [comment]
默认的教程感觉很多错误，运行不起来怎么办？

**Comment by hufeng** [comment]
import {DubboService} from 'apache-dubbo-service'

**Comment by hufeng** [comment]
https://www.yuque.com/foow4t/ngd5zk/ais1d1

**Comment by oeliok** [comment]
> https://www.yuque.com/foow4t/ngd5zk/ais1d1

![image](https://user-images.githubusercontent.com/15521896/128521597-12ae5502-089d-474d-a273-1ab84f36b8b8.png)
遇到这样的问题怎么回事呢？

**Comment by oeliok** [comment]
> > https://www.yuque.com/foow4t/ngd5zk/ais1d1
> 
> ![image](https://user-images.githubusercontent.com/15521896/128521762-6e440d67-c4d5-40fa-b04d-f154e98172f5.png)
> 
> 遇到这样的问题怎么回事呢？

我知道原因了helloservice没有加ruturn
const HelloService = (dubbo: Dubbo) => {
    return dubbo.proxyService<IHelloService>({
        dubboInterface: 'org.apache.dubbo.service.HelloService',
        methods: {
            sayHello(name: string) {
                return [name];
            }
        }
    });
};

**Comment by oeliok** [comment]
> https://www.yuque.com/foow4t/ngd5zk/ais1d1

![image](https://user-images.githubusercontent.com/15521896/128524180-183e77e3-7dbb-42af-b89a-1d72842539f6.png)
请问这个是什么错误呢

**Comment by oeliok** [comment]
$ node provider.js 
(node:7568) UnhandledPromiseRejectionWarning: Error: -101 no node
    at callback (E:\workplace\dubbojs\node_modules\_zookeeper@4.10.0@zookeeper\lib\zk_promise.js:207:28)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


感觉很多错误，无法运行程序，而且DubboService.start也没有

**Comment by hufeng** [comment]
方法的参数使用 java.String包装下

import java from 'js-to-java' // 或者 import {java} from
'apache-dubbo-consumer'

dubbo.service.HelloService.sayHello(java.String('mmm'))

oeli ***@***.***> 于2021年8月6日周五 下午11:04写道：

**Comment by hufeng** [comment]
可以整理一个简化的demo放在github吗 ， 可以一起看下

feng hu ***@***.***> 于2021年8月9日周一 下午2:27写道：
