### ISSUE TITLE
apache-dubbo-consumer 的 Dubbo 调用 proxyService 方法无效果

### ISSUE THREAD

**Issue by KenyeeC** [apache/dubbo-js#254]
看了 duubo.ts 的代码发现 [proxyService](https://github.com/apache/dubbo-js/blob/28e499b0b5e9e862945ad3d7461cba34e233f82f/packages/dubbo-consumer/src/dubbo.ts#L209) 方法只是单纯的返回自己，与 DubboDirectlyInvoker 的实例的 proxyService 表现不一样，希望有相同的表现，或者可以将 [consumeService](https://github.com/apache/dubbo-js/blob/28e499b0b5e9e862945ad3d7461cba34e233f82f/packages/dubbo-consumer/src/dubbo.ts#L113) 改为 public 的方法

**Comment by hufeng** [comment]
+1
