### ISSUE TITLE
can support dubbo3.0 

### ISSUE THREAD

**Issue by itzzit** [apache/dubbo-js#258]
能否支持dubbo3.0版本，我本地调用一直超时，是不是版本问题呢
const demoProvider = (dubbo) => dubbo.proxyService({
    dubboInterface: 'com.pupu.property.api.IDubboDemoApi',
    version: "1.0.0",
    methods: {
        hello(hello: string) {
            return [
                java.String(hello)
            ]
        },
    },
})
const setting = dubboSetting
    .match(
        'com.pupu.property.api.IDubboDemoApi',
        {
            version: '1.0.0',
            group:"DEFAULT_GROUP",
        },
    )
const service = {
    demoProvider
}
const dubbo = new Dubbo<typeof service>({
    registry: Nacos({
        connect: "192.168.31.239:8848",
        namespace: "public",
        logger: console,
    }),
    services: service,
    application: { name: 'dubbo-js' },
    dubboSetting: setting,
    dubboVersion: "3.0.3",
    dubboInvokeTimeout: 100000,
})
export default dubbo

**Comment by hufeng** [comment]
目前只支持dubbo2，dubbo3正在开发中～
