### ISSUE TITLE
请问apache-dubbo-consumer 是否支持直连，没有找到对应的API

### ISSUE THREAD

**Issue by springJia** [apache/dubbo-js#259]
类似之前的DirectlyDubbo.from

**Comment by justxuewei** [comment]
支持直连，可以查看 https://github.com/apache/dubbo-go/blob/cc7af1151318d025eb4238cec5674b24a551b276/config/reference_config.go#L50。

**Comment by justxuewei** [comment]
cc @LaurenceLiZhixin @zhaoyunxing92 配置文件可能需要更详细的文档
