### ISSUE TITLE
基础项目脚手架代码的搭建 （ typescript pnpm monorepo vitest nx）

### ISSUE THREAD

**Issue by hufeng** [apache/dubbo-js#288]

**Comment by hufeng** [comment]
Merge #285

**Comment by hufeng** [comment]
@godkun 详细说明下，目前的基础项目的技术搭建使用方式

- 技术上
- 流程上

**Comment by godkun** [comment]
> 
好滴，这两天搞定

**Comment by godkun** [comment]
> @godkun 详细说明下，目前的基础项目的技术搭建使用方式
> 
> * 技术上
> * 流程上

好滴，这两天搞定

**Comment by hufeng** [comment]
好的，完成之后，同步社区，close issue

godkun 在 2022年10月24日 星期一 14:23:53 (+08:00) 写道：



@godkun 详细说明下，目前的基础项目的技术搭建使用方式

技术上
流程上

好滴，这两天搞定

**Comment by hufeng** [comment]
- 开发语言：Typescript
- 单元测试框架：Vitest
- 模块依赖管理：pnpm
- 项目管理：mono repo + pnpm workspace
- 构建管理：nx
- 项目提交检查：husky （检查code style，test suites）
- 项目流水线
   -  pnpm test - run all module test suites
   - pnpm test:watch - run all module test suites with watch mode
   - pnpm build -  build all module
   - pnpm ts-cehck - check all module typescript types 
   - pnpm format - format all ts/tsx/md/js/json
