### ISSUE TITLE
请问支持服务注册发现、负载均衡等服务治理能力吗？

### ISSUE THREAD

**Issue by mrwangyin** [apache/dubbo-js#390]
请问支持服务注册发现、负载均衡等服务治理能力吗？

**Comment by jianyi-gronk** [comment]
It is not supported yet, but it is already planned.

**Comment by mrwangyin** [comment]
> It is not supported yet, but it is already planned.

你好，请问 [Apache Dubbo-js 4.0.0 released](https://github.com/apache/dubbo-js/releases/tag/4.0.0) 能发布到npm仓库吗？
