### ISSUE TITLE
may we have to implement a timeout when reconnecting

### ISSUE THREAD

**Issue by hsiaosiyuan0** [apache/dubbo-js#57]
**Is your feature request related to a problem? Please describe.**

在这里进行 [重连]( https://github.com/dubbo/dubbo2.js/blob/master/packages/dubbo/src/socket-worker.ts#L239) 的时候，我们是否应该像这里描述的一样 https://github.com/nodejs/node/issues/5757#issuecomment-305969057 增加一个超时的机制，否则，代码可能需要增加类似下面的逻辑

```js
if (this._retry > 0) {
  if (IS_RECONNECTING) return;
  // reconnecting...
 } else {
   ...
 }
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hufeng** [comment]
cool!

**Comment by hufeng** [comment]
welcome pull request 😃

**Comment by DanielYWoo** [comment]
我是#5757的提出者, 我当时的诉求是我的某个应用里connection timeout比较短, 但是socket timeout比较长, 但是目前nodejs并不支持.
你们估计需要在 [_initSocket](https://github.com/apache/dubbo-js/blob/master/packages/dubbo/src/socket-worker.ts#L165) 里面通过global.setTimeout(不是socket.setTimeout)去注册一下onClose, 然后onConnect里clearTimeout.

**Comment by hsiaosiyuan0** [comment]
@DanielYWoo 感谢提醒，不过我刚刚去看了源码，`socket.setTimeout` 应该大体上和你建议的方式差不多，调用过程如下：

* https://github.com/nodejs/node/blob/1447a79dc435578bffba32ead9b2ffa0425fc30a/lib/net.js#L452
* https://github.com/nodejs/node/blob/4aca277f16b8649b5fc21d41f340fad0a47c2e61/lib/internal/stream_base_commons.js#L240
* https://github.com/nodejs/node/blob/4aca277f16b8649b5fc21d41f340fad0a47c2e61/lib/internal/timers.js#L345

到了这边会发现会实例化一个定时器，而这个定时器在未来 `stream.onRead` 或者 `stream.onWrite` 的时候，会被刷新，所以从代码上来看，应该会和 https://github.com/nodejs/node/issues/5757#issuecomment-305969057 中 bnoordhuis 的结果一样

**Comment by DanielYWoo** [comment]
👍
