### ISSUE TITLE
nacos  config 支持

### ISSUE THREAD

**Issue by rocky-zh** [apache/dubbo-js#73]
nacos 0.6最新版本 开始支持dubbo 服务注册中心，希望能与alibaba dubbo生态有较好的融合

**Comment by hufeng** [comment]
@rocky-zh 我来研究下 按照现在的理解应该是替换掉node zookeeper的模块保持接口不变 然后node可以和nacos连接。

**Comment by hufeng** [comment]
@rocky-zh 现在有考虑线上的场景使用nacos嘛

**Comment by rocky-zh** [comment]
@hufeng 我司正在关注，估计明年 会开始启动线上小项目实践

**Comment by hufeng** [comment]
等待node和nacos生态的集成

**Comment by rocky-zh** [comment]
nacos 有 nodejs的sdk
[https://github.com/nacos-group/nacos-sdk-nodejs]

**Comment by hufeng** [comment]
@rocky-zh 帅，我来学习下，抽时间集成起来，因为我们现在还没有线上场景，还请@rocky-zh多一点测试

**Comment by hufeng** [comment]
开始准备dubbo2.js 对naco的支持

作为注册中心的方案会很多比如zookeeper, redis, etcd,consul, nacos

对于dubbo2.js来说，更希望贴近dubbo的方案，所以我们支持zookeeper和nacos

对于其他的注册中心方案 是不是 由社区来提供 我们提供可以插拔的机制和方案

不过目前上游dubbo@2.7* 版本 提供了对nacos的支持，我们先要确保dubbo2.js 跟上dubbo2.7的版本变化



@rocky-zh @creasy2010

**Comment by rocky-zh** [comment]
期待 ing，可以跟我司 @lileilei 同学多多沟通，他应该有很多想法。

**Comment by rocky-zh** [comment]
兄弟，社区都在前进，我建议您选举新的项目管理者，继续dubbo-js的版本迭代。

**Comment by ralf0131** [comment]
@rocky-zh  The Dubbo community welcomes anyone to contribute. You can improve it if you have interest.

**Comment by rocky-zh** [comment]
你应该推进这件事情，6个月过去了，nacos依然不支持。作为一个项目的owner

**Comment by ralf0131** [comment]
@rocky-zh I did not know about this issue before. I agree that project should set up roadmap in order to attract more user to participate, let's work with the node-js maintainers to figure it out. However, please be aware that every single contribution is made by the volunteers. So it is highly possible that the schedule may not be accomplished in time.

**Comment by rocky-zh** [comment]
期待有好的进展，社区如果没有人组织这些事情，这个项目很快就会自生自灭
我看过zk的注册中心实现，如果要抽取出来，确实需要原创做一个大的重构

**Comment by hufeng** [comment]
@rocky-zh @ralf0131  

1. https://github.com/apache/dubbo-js/pull/117  我们可以一起review下.

2. 不是支持nacos，之前去调研的时候写的还不完整 issue还有不少 star不多 每个月的download也很少 所以就在等成熟度 这点 @ralf0131 可以一起看下 应该也是阿里的同学在维护

3. 年后回来我个人确实工作上变化很大，为了赶一个项目通宵周末全在里面，4.5月又经历了离职 找工作
生活不永远都是阳光灿烂。

@rocky-zh @lileilei 同学都非常棒，希望能一起把这个项目维护好。

**Comment by CoderPoet** [comment]
目前还不支持nacos吧？

**Comment by lavyun** [comment]
我司 dubbo 已经在升 2.7 了，等待支持 nacos

**Comment by yidafu** [comment]
Hi, there is any progress about supporting naccos. I would like to have a try. @hufeng

**Comment by hufeng** [comment]
yes!
