### ISSUE TITLE
Node进程会偶尔与zk集群断开连接,导致socket无可用agent

### ISSUE THREAD

**Issue by yinggaozhen** [apache/dubbo-js#80]
- 操作系统 : Centos7.2
- Node : 8.5.0
- Dubbo2.js : 2.3.6
- pm2 : 2.8.0

遇到一个很奇怪的问题,线上有5台均为可用的zk服务构成的集群,在极偶发情况下,对节点进行起停服务时,过大约5分钟左右,会引发部分Node机器与zk断开连接,且再也无法进行重连,导致watch事件后续接收到的信息都是empty agentlist.重启node进程之后立即恢复(此举可基本排除zk不可用的可能性).而且此类问题已在半个月内连续发生**2**次,最后都是通过重启服务得到解决.

**问题复现**:

想要对问题进行复现,但是无论是对zk进行停止服务/dubbo服务节点注册&注销/摘光一个下所有服务节点,均无法复现.

**目前的解决方法(暂行)**:
目前是在onTrace回调函数中,如果检测到message为`agentList is empty` 时.上报异常并执行process.exit(-1), 再借由pm2守护进程的能力进行重启,以达到恢复服务的目的,但是这种做法实属下下策

**请问有什么更加优雅的方法解决这个问题?**

相关日志 : 
```
{ time: '2019-01-08T02:34:48.356Z',
  pid: 26466,
  host: '1.1.1.2',
  type: 'ERR',
  msg:
   Error: SocketWorker#47 <=closed=> 1.1.1.2:20880 hadError: true retry: 0
       at SocketWorker._onClose (/node/node_modules/dubbo2.js/es7/socket-worker.js:76:29) }
{ time: '2019-01-08T02:34:48.356Z',
  pid: 26466,
  host: '1.1.1.2',
  type: 'ERR',
  msg:
   Error: socket-worker#1.1.1.2:20880 was closed. delete this socket worker
       at DubboAgent._clearCloseWorker (/node/node_modules/dubbo2.js/es7/dubbo-agent.js:75:29) }

    at ConnectionManager.queue (/node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:720:28)
{
    at ConnectionManager.queue (/node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:720:28)
  code: -4,
  name: 'CONNECTION_LOSS',
  path: undefined,
  message: 'Exception: CONNECTION_LOSS[-4]',
  host: '1.1.1.2',
  time: '2019-01-08T02:38:07.056Z' }
Error: trigger watch NODE_CHILDREN_CHANGED[4]@/dubbo/com.MemberService/providers agentList is empty
    at EventEmitter.<anonymous> (/node/node_modules/dubbo2.js/es7/zookeeper.js:289:33)
{ Error: trigger watch NODE_CHILDREN_CHANGED[4]@/dubbo/com.MemberService/providers agentList is empty
    at EventEmitter.<anonymous> (/node/node_modules/dubbo2.js/es7/zookeeper.js:289:33) host: '1.1.1.2', time: '2019-01-08T02:38:07.061Z' }
Error: agentAddrList-> could not find any avaliable socekt worker
    at DubboAgent.getAvailableSocketWorker (/node/node_modules/dubbo2.js/es7/dubbo-agent.js:95:29)
{ Error: agentAddrList-> could not find any avaliable socekt worker
    at DubboAgent.getAvailableSocketWorker (/node/node_modules/dubbo2.js/es7/dubbo-agent.js:95:29) host: '1.1.1.2', time: '2019-01-08T02:38:07.164Z' }
Error: uuid:  invoke com.MemberService#getMemberByUid was error, requestId#289360:Could not find any agent worker with com.MemberService#0.0.0# agentList:
    at Scheduler._handleDubboInvoke (/node/node_modules/dubbo2.js/es7/scheduler.js:173:25)
{ Error: uuid:  invoke com.MemberService#getMemberByUid was error, requestId#289360:Could not find any agent worker with com.MemberService#0.0.0# agentList:
    at Scheduler._handleDubboInvoke (/node/node_modules/dubbo2.js/es7/scheduler.js:173:25) host: '1.1.1.2', time: '2019-01-08T02:38:07.165Z' }
Error: agentAddrList-> could not find any avaliable socekt worker
    at DubboAgent.getAvailableSocketWorker (/node/node_modules/dubbo2.js/es7/dubbo-agent.js:95:29)
{ Error: agentAddrList-> could not find any avaliable socekt worker
    at DubboAgent.getAvailableSocketWorker (/node/node_modules/dubbo2.js/es7/dubbo-agent.js:95:29) host: '1.1.1.2', time: '2019-01-08T02:38:07.247Z' }
Error: uuid:  invoke com.MemberService#getMemberByUid was error, requestId#289362:Could not find any agent worker with com.MemberService#0.0.0# agentList:
    at Scheduler._handleDubboInvoke (/node/node_modules/dubbo2.js/es7/scheduler.js:173:25)
{ Error: uuid:  invoke com.MemberService#getMemberByUid was error, requestId#289362:Could not find any agent worker with com.MemberService#0.0.0# agentList:
    at Scheduler._handleDubboInvoke (/node/node_modules/dubbo2.js/es7/scheduler.js:173:25) host: '1.1.1.2', time: '2019-01-08T02:38:07.247Z' }
Error: agentAddrList-> could not find any avaliable socekt worker
    at DubboAgent.getAvailableSocketWorker (/node/node_modules/dubbo2.js/es7/dubbo-agent.js:95:29)
{ Error: agentAddrList-> could not find any avaliable socekt worker
    at DubboAgent.getAvailableSocketWorker (/node/node_modules/dubbo2.js/es7/dubbo-agent.js:95:29) host: '1.1.1.2', time: '2019-01-08T02:38:07.283Z' }

```

**Comment by hufeng** [comment]
@yinggaozhen 感谢feedback, 我们也出现过类似的情况，node-zookeeper-client的watch稳定性感觉好像差了一点，有时候watch的时候获取的agentlist 就是empty，所以现在代码是延时2s去获取children，不过这个在本地不是特别好复现。

**Comment by hufeng** [comment]
在脑海中思索是不是每次watch的时候不去getChildren而是根据事件类型去add或者delete我们的dubbourl比较精确一点

**Comment by hufeng** [comment]
@yinggaozhen 希望可以尽快折腾出来zookeeper的docker集群，更方便的捕捉这个问题

**Comment by yinggaozhen** [comment]
@hufeng  赞！现在仍然每天都有大量类似的报错

目前采取的方法是在监听到此类错误之后立马重启进程，就会恢复正常

**Comment by hufeng** [comment]
@yinggaozhen 非常抱歉，手头不太好复现，导致问题迟迟不能fixed。

**Comment by hufeng** [comment]
@sunchuanleihit 三石同学 我们一起关注下这个问题 目前我在仓库里面放了一个docker-compose.yml

方便建议集群测试 目前还是没有复现 不过我把zookeeper.ts重构了下 发现之前也有不合理的地方

**Comment by hufeng** [comment]
很想把这个问题fixed掉，log里面这个-4 我找到了源码中对应的代码

```text
{
    at ConnectionManager.queue (/node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:720:28)
  code: -4,
  name: 'CONNECTION_LOSS',
  path: undefined,
  message: 'Exception: CONNECTION_LOSS[-4]',
  host: '1.1.1.2',
  time: '2019-01-08T02:38:07.056Z' }
```

![image](https://user-images.githubusercontent.com/533008/59337551-6b074d80-8d33-11e9-9705-e465999ab627.png)


标记的状态是认证失败，也就是node的zk 连不上server端了 导致每次查询的时候都是拿一个空的agentList去匹配可用的socket-worker节点。

**Comment by hufeng** [comment]
基本理清楚问题所在 根源问题是zk为什么会断掉 然后dubbo2.js针对获取children处理的要再细腻一点

**Comment by hsiaosiyuan0** [comment]
发现一个 "似乎是" 的复现步骤。

首先在本地启动一个可以运行的实例：

```bash
# start docker
$ docker-compose up 
# start providers
$ java -jar target/dubbo-demo-provider-2.6.3-jar-with-dependencies.jar
# start example/hello-koa
$ npm run debug:start
```

详细的启动步骤参考 [for-contributors](https://github.com/apache/dubbo-js#for-contributors)

在复现问题前，确保实例已经运行起来：

```bash
curl http://localhost:3000/hello
```

如果看到 `Hello World` 的话，则可以开始复现问题

第一步，手动删除 `/dubbo` 节点

```bash
```bash
# replace below port according your env
zkcli -server localhost:2182
# check what's in our ZK
ls /
# delete node `/dubbo`
rmr /dubbo/com.alibaba.dubbo.demo.BasicTypeProvider/consumers
rmr /dubbo/com.alibaba.dubbo.demo.ErrorProvider
rmr /dubbo
# check `/dubbo` has been deleted if it isn't in the output of below command
ls /
```

第二步，停止 java providers，可以 `kill -9 pid` 或 `CTRL+C`
第三步，启动 java providers，启动命令和之前的一样

此时再次通过：

```bash
curl http://localhost:3000/hello
```

会得到输出：

```
uuid:  invoke com.alibaba.dubbo.demo.DemoProvider#sayHello was error, Zookeeper Can not be find any agents
```

根据输出发现，node 和 ZK 之间的连接是通的，但是无法连接到 java providers

此时重启 node，然后再次运行上面的 curl 命令，会发现 node 可以连接到 java providers，故障已经排除

**Comment by hufeng** [comment]
@yinggaozhen 还有更全面的一点log嘛

**Comment by yinggaozhen** [comment]
@Zewail 提供一下更全面的日志

**Comment by hufeng** [comment]
翻看node-zookeeper-client的源码 导致connection loss应该是出现了session exipred.

**Comment by rocky-zh** [comment]
亲，然后呢，我们已经频繁的碰倒这个问题

> 翻看node-zookeeper-client的源码 导致connection loss应该是出现了session exipred.

**Comment by hsiaosiyuan0** [comment]
@rocky-zh 请提供问题出现阶段的 zookeeper 日志和 dubbo-js 日志用于定位具体问题

**Comment by hufeng** [comment]
@rocky-zh 我本地尝试了很多的复现 也看了代码 觉得session exipired概率很高 还是想如果有log 我就可以直接fixed了。

**Comment by rocky-zh** [comment]
> zookeeper

我们的provider是在k8s里边运行，只要进行删除运行的provider实例，k8s自动重建pods时，dubbo-js就会抛出Could not find any agent worker。目前是采用前端实例也自动重启解决

**Comment by hufeng** [comment]
@rocky-zh 等着这个fixed 然后zk分拆一个单独的包 发布新的dubbo-js版本 为后面快速支持nacos做准备了

**Comment by hufeng** [comment]
我来先针对session expired来fixed下

**Comment by rocky-zh** [comment]
> 我来先针对session expired来fixed下

坐等坐等

**Comment by hufeng** [comment]
@rocky-zh 我们用的node-zookeeper-client 里面的实现状态转换非常多 不细心不注意就会产生无限连接 然后占满zookeeper server的链接

**Comment by rocky-zh** [comment]
[](https://wiki.apache.org/hadoop/ZooKeeper/FAQ#A3)

3. How should I handle SESSION_EXPIRED?

SESSION_EXPIRED automatically closes the ZooKeeper handle. In a correctly operating cluster, you should never see SESSION_EXPIRED. It means that the client was partitioned off from the ZooKeeper service for more the the session timeout and ZooKeeper decided that the client died. Because the ZooKeeper service is ground truth, the client should consider itself dead and go into recovery. If the client is only reading state from ZooKeeper, recovery means just reconnecting. In more complex applications, recovery means recreating ephemeral nodes, vying for leadership roles, and reconstructing published state.

Library writers should be conscious of the severity of the expired state and not try to recover from it. Instead libraries should return a fatal error. Even if the library is simply reading from ZooKeeper, the user of the library may also be doing other things with ZooKeeper that requires more complex recovery.

Session expiration is managed by the ZooKeeper cluster itself, not by the client. When the ZK client establishes a session with the cluster it provides a "timeout" value. This value is used by the cluster to determine when the client's session expires. Expirations happens when the cluster does not hear from the client within the specified session timeout period (i.e. no heartbeat). At session expiration the cluster will delete any/all ephemeral nodes owned by that session and immediately notify any/all connected clients of the change (anyone watching those znodes). At this point the client of the expired session is still disconnected from the cluster, it will not be notified of the session expiration until/unless it is able to re-establish a connection to the cluster. The client will stay in disconnected state until the TCP connection is re-established with the cluster, at which point the watcher of the expired session will receive the "session expired" notification.

Example state transitions for an expired session as seen by the expired session's watcher:

'connected' : session is established and client is communicating with cluster (client/server communication is operating properly)
.... client is partitioned from the cluster
'disconnected' : client has lost connectivity with the cluster
.... time elapses, after 'timeout' period the cluster expires the session, nothing is seen by client as it is disconnected from cluster
.... time elapses, the client regains network level connectivity with the cluster
'expired' : eventually the client reconnects to the cluster, it is then notified of the expiration

**Comment by hufeng** [comment]
@rocky-zh 这个我看过 包括这个issue https://github.com/alexguan/node-zookeeper-client/issues/20  从@yinggaozhen提供的日志来看 确实存在connection-lose的情况，node-zookeeper-client内部其实如果断开了连接会无限重连按道理不应该出现connection lose, 当状态为session expired时候不会去重连，
 还是因为在watch的瞬间出现了connection lose   。

推测：
1. session expired. 导致不会重连 后续收不到watch事件
2. watch的时候出现connection-lose, 代码的不合理导致注册信息清空，但后续为啥再没有watch事件收到呢

因为没有具体的log，导致我也迟迟没有办法fixed掉这个问题。

**Comment by rocky-zh** [comment]
![image](https://user-images.githubusercontent.com/1244039/59961477-c6db8e80-950a-11e9-8a26-111a7e5bc302.png)
这个是我们某次发生的故障截图

**Comment by hufeng** [comment]
已经提交一个pr, https://github.com/apache/dubbo-js/pull/121 

@hsiaosiyuan0 @rocky-zh 可以帮我review下

@rocky-zh 这个log只是调用的log，看不到zk的状态 等新的pr合并后，我来找阿里的同学发布一个新的版本 到时候可以这样，(现在的版本也有 只是log的信息比较大 新版本我精简了下)

```javascript
dubbo.subscribe({
 onTrace(msg) {
   //log
  log.error(msg);
}
})
```

**Comment by rocky-zh** [comment]
@hufeng  需要发布一个realease tag出来，不然我们打包就很复杂了

**Comment by wushanchao** [comment]
> 发现一个 "似乎是" 的复现步骤。
> 
> 首先在本地启动一个可以运行的实例：
> 
> ```shell
> # start docker
> $ docker-compose up 
> # start providers
> $ java -jar target/dubbo-demo-provider-2.6.3-jar-with-dependencies.jar
> # start example/hello-koa
> $ npm run debug:start
> ```
> 
> 详细的启动步骤参考 [for-contributors](https://github.com/apache/dubbo-js#for-contributors)
> 
> 在复现问题前，确保实例已经运行起来：
> 
> ```shell
> curl http://localhost:3000/hello
> ```
> 
> 如果看到 `Hello World` 的话，则可以开始复现问题
> 
> 第一步，手动删除 `/dubbo` 节点
> 
> ```shell
> ```bash
> # replace below port according your env
> zkcli -server localhost:2182
> # check what's in our ZK
> ls /
> # delete node `/dubbo`
> rmr /dubbo/com.alibaba.dubbo.demo.BasicTypeProvider/consumers
> rmr /dubbo/com.alibaba.dubbo.demo.ErrorProvider
> rmr /dubbo
> # check `/dubbo` has been deleted if it isn't in the output of below command
> ls /
> ```
> 
> 第二步，停止 java providers，可以 `kill -9 pid` 或 `CTRL+C`
> 第三步，启动 java providers，启动命令和之前的一样
> 
> 此时再次通过：
> 
> ```shell
> curl http://localhost:3000/hello
> ```
> 
> 会得到输出：
> 
> ```
> uuid:  invoke com.alibaba.dubbo.demo.DemoProvider#sayHello was error, Zookeeper Can not be find any agents
> ```
> 
> 根据输出发现，node 和 ZK 之间的连接是通的，但是无法连接到 java providers
> 
> 此时重启 node，然后再次运行上面的 curl 命令，会发现 node 可以连接到 java providers，故障已经排除
> 
> 虽然上述复现步骤的报错信息和前面的 issue 中的 log 内容不同，不过不能排除前面的 log 有可能和问题并不对应，又或者该复现步骤反应了新的问题

操作系统 : Centos7.2
Node : 10.16.0
Dubbo2.js : 2.3.9

我本机可重现你的问题。

**Comment by hsiaosiyuan0** [comment]
@wushanchao 因为 OP 没有给复现步骤，这是我推测的一个情况，肯定是能复现我才贴出来

**Comment by hufeng** [comment]
dubbo-js@3.0.0合入了针对性的pr，应该可以解决这个问题

**Comment by PraiseSong** [comment]
> dubbo-js@3.0.0合入了针对性的pr，应该可以解决这个问题

预计啥时候发布呀

**Comment by hufeng** [comment]
@PraiseSong 已经在走发布投票流程

**Comment by luruozhou** [comment]
> 很想把这个问题fixed掉，log里面这个-4 我找到了源码中对应的代码
> 
> ```
> {
>     at ConnectionManager.queue (/node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:720:28)
>   code: -4,
>   name: 'CONNECTION_LOSS',
>   path: undefined,
>   message: 'Exception: CONNECTION_LOSS[-4]',
>   host: '1.1.1.2',
>   time: '2019-01-08T02:38:07.056Z' }
> ```
> 
> ![image](https://user-images.githubusercontent.com/533008/59337551-6b074d80-8d33-11e9-9705-e465999ab627.png)
> 
> 标记的状态是认证失败，也就是node的zk 连不上server端了 或者连上了但是拒绝查询children导致每次查询的时候都是拿一个空的agentList去匹配可用的socket-worker节点。

这里的 -4 是Exception.js里的状态，代表CONNECTION_LOSS。。。

**Comment by luruozhou** [comment]
节点启停会造成 zk-client对 zk进行重连，如果在重连过程中对节点进行 getChildren操作，就有可能造成 connection loss. 此时节点的watcher就会设置不上，后续节点的children变更就拿不到了.

**Comment by wushanchao** [comment]
> 节点启停会造成 zk-client对 zk进行重连，如果在重连过程中对节点进行 getChildren操作，就有可能造成 connection loss. 此时节点的watcher就会设置不上，后续节点的children变更就拿不到了.

那等待重连完成后，再去getChildren一下？

**Comment by luruozhou** [comment]
> > 节点启停会造成 zk-client对 zk进行重连，如果在重连过程中对节点进行 getChildren操作，就有可能造成 connection loss. 此时节点的watcher就会设置不上，后续节点的children变更就拿不到了.
> 
> 那等待重连完成后，再去getChildren一下？

对的, getChildren的回调里需要处理一下CONNECTION_LOSS,重新getChildren.

**Comment by luruozhou** [comment]
还有种情况会导致拿不到服务列表，情况是provider没有注册到zk上，但与本issue无关。
https://github.com/apache/zookeeper/pull/304
出现场景是 zk服务器故障，provider重连zk创建节点， 却由于之前的临时节点未删除返回NodeExists异常，provider误以为服务注册成功。 后续故障服务器恢复删除了临时节点，导致实际上服务注册列表为空。

**Comment by wushanchao** [comment]
> > > 节点启停会造成 zk-client对 zk进行重连，如果在重连过程中对节点进行 getChildren操作，就有可能造成 connection loss. 此时节点的watcher就会设置不上，后续节点的children变更就拿不到了.
> > 
> > 
> > 那等待重连完成后，再去getChildren一下？
> 
> 对的, getChildren的回调里需要处理一下CONNECTION_LOSS,重新getChildren.

大佬，发个pr造福下大家？

**Comment by luruozhou** [comment]
> > > > 节点启停会造成 zk-client对 zk进行重连，如果在重连过程中对节点进行 getChildren操作，就有可能造成 connection loss. 此时节点的watcher就会设置不上，后续节点的children变更就拿不到了.
> > > 
> > > 
> > > 那等待重连完成后，再去getChildren一下？
> > 
> > 
> > 对的, getChildren的回调里需要处理一下CONNECTION_LOSS,重新getChildren.
> 
> 大佬，发个pr造福下大家？

我尝试解决一下哈,水平有限

**Comment by luruozhou** [comment]
@wushanchao 帮忙review一下

**Comment by wushanchao** [comment]
> @wushanchao 帮忙review一下

👍👍👍

**Comment by wushanchao** [comment]
@luruozhou  👍👍👍

**Comment by 178518** [comment]
dubbo-js@3.0.0版本什么时候发布，我生产环境也碰到这个问题。

**Comment by hufeng** [comment]
apache-dubbo-js@3.0.0-rc6
