### ISSUE TITLE
想问一下，对于路由规则后续会有计划支持吗

### ISSUE THREAD

**Issue by lavyun** [apache/dubbo-js#88]

**Comment by hufeng** [comment]
@lavyun 能详细描述下嘛

**Comment by lavyun** [comment]
@hufeng 这里有说明 http://dubbo.apache.org/zh-cn/docs/user/demos/routing-rule.html 和 http://dubbo.apache.org/zh-cn/docs/source_code_guide/router.html 我们公司有dubbo隔离，底层依赖的是消费者的

**Comment by hufeng** [comment]
@lavyun 好的 我来看看

**Comment by lwsbox** [comment]
支持标签路由功能么
