### ISSUE TITLE
请问下，是否有计划支持其他注册中心

### ISSUE THREAD

**Issue by height1987** [apache/dubbo-js#92]
很希望能有redis注册中心的支持，请问下，有相关的排期计划吗？ 
谢谢

**Comment by hufeng** [comment]
@height1987 hi 正在调研支持naco，redis我来看下

**Comment by hufeng** [comment]
hi @height1987 如果你这边对redis有非常成熟的方案，欢迎pr

**Comment by height1987** [comment]
感谢，不过我们暂时还没有成熟的方案，期待你们的排期

**Comment by hufeng** [comment]
+1

height1987 <notifications@github.com> 于2019年4月24日周三 下午3:23写道：

**Comment by baodingfengyun** [comment]
希望支持nacos

**Comment by hufeng** [comment]
Yes

风云0312 <notifications@github.com> 于2019年7月9日周二 上午10:18写道：
